{"spider": "https://d.kstore.dev/download/11050/v.jar",
"wallpaper": "https://深色壁纸.xxooo.cf/",
"logo": "./logo.png",
"sites": [
{"key": "豆瓣","name": "爱无｜止境","type": 3,"api": "csp_Douban","searchable": 0},
{"key": "热播影视","name": "热播｜APP","type": 3,"api": "csp_AppRJ","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": {
"url": "http://v.rbotv.cn"}},
{"key": "农牧","name": "农牧｜APP","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./XYQHiker/农牧影视.json"},
{"key": "快手直播","name": "快手｜直播","type": 3,"api": "csp_KsLive","searchable": 0,"jar": "./jar/spider.jar","quickSearch": 0,"filterable": 1,"style": {"type": "rect","ratio": 1.597}},
{"key": "虎牙","name": "虎牙｜直播","type": 3,"api": "./drpy_libs/drpy22.min.js","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./js/虎牙.js"},
{"key": "斗鱼js","name": "斗鱼｜直播","type": 3,"api": "./drpy_libs/drpy22.min.js","ext": "./js/斗鱼.js","style": {"type": "rect","ratio": 1.755},"playerType": "2","searchable": 0,"quickSearch": 0,"changeable": 0},
{"key": "流光","name": "流光｜APP","type": 3,"api": "csp_XBPQ","ext": "./XBPQ/流光4k.json"},
{"key": "哔哩视频","name": "哔哩｜视频","type": 3,"api": "csp_BiliYS","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0,"style": {"type": "rect","ratio": 1.433},"ext": {"json": "./json/哔哩视频.json","cookie": "http://127.0.0.1:9978/file/TVBox/bili_cookie.txt"}},
{"key": "七七影视","name": "七七｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/七七影视.json"},
{"key": "永乐影视","name": "永乐｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/永乐影视.json"},
{"key": "雪糕影视","name": "雪糕｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/雪糕影视.json"},
{"key": "随客影视","name": "随客｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/随客影视.json"},
{"key": "秀儿影视","name": "秀儿｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/秀儿影视.json"},
{"key": "星芽短剧","name": "星芽｜短剧","type": 3,"api": "./drpy_libs/drpy2.min.js","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./js/星芽短剧.js"},
{"key": "悟空","name": "悟空｜影视","type": 3,"api": "csp_XBPQ","searchable": 1,"click": "document.querySelector(\"#playleft iframe\").contentWindow.document.querySelector(\"#start\").click();","quickSearch": 1,"filterable": 1,"ext": "./XBPQ/悟空影视.json"},
{"key": "路飞影视","name": "路飞｜影视","type": 3,"api": "csp_HBPQ","ext": "./XBPQ/路飞影视.json"},
{"key": "全集影视","name": "网集｜影视","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./XYQHiker/全集影视.json"},
{"key": "1905","name": "1905｜影视","type": 3,"api": "csp_Web1905","searchable": 1,"quickSearch": 1,"filterable": 0},
{"key": "恰瓜子","name": "恰恰｜影视","type": 3,"api": "./drpy_libs/drpy2.min.js","ext": "./js/恰瓜子.js"},
 {"key": "恰娃子","name": "娃娃｜影视","type": 3,"api": "./drpy_libs/drpy2.min.js","ext": "./js/瓜娃子.js"},
{"key": "腾讯视频","name": "腾讯｜视频","type": 3,"api": "./js/drpy2.min.js","ext": "./js/腾讯视频.js"},
{"key": "优酷视频","name": "优酷｜视频","type": 3,"api": "./js/drpy2.min.js","ext": "./js/优酷视频.js"},
{"key": "芒果视频","name": "芒果｜视频","type": 3,"api": "./js/drpy2.min.js","ext": "./js/芒果视频.js"},
{"key": "爱奇艺","name": "爱奇异｜视频","type": 3,"api": "./js/drpy2.min.js","ext": "./js/爱奇艺.js"},
{"key": "三六零","name": "三六零｜视频","type": 3,"api": "csp_SP360"},
{"key": "蜻蜓FM","name": "蜻蜓｜FM","type": 3,"api": "./js/drpy2.min.js","ext": "./js/蜻蜓FM.js"},
{"key": "比赛看球","name": "比赛｜看球","type": 3,"api": "csp_Kanqiu","gridview": 3,"style": {"type": "list"}},
{"key": "88看球","name": "88｜看球","type": 3,"api": "./js/drpy2.min.js","style": {
"type": "list"},"ext": "./js/88看球.js"},
{"key": "博看听书网","name": "博看｜小说","type": 3,"api": "./drpy_libs/drpy2.min.js","searchable": 1,"quickSearch": 1,"filterable": 1,"order_num": 0,"ext": "./js/博看听书.js"},
{"key": "兔小贝","name": "兔小贝｜幼教","type": 3,"api": "./js/drpy2.min.js","ext": "./js/兔小贝.js","style": {"type": "rect","ratio": 1.597}},
{"key": "贝乐虎","name": "贝乐虎｜幼教","type": 3,"api": "./js/drpy2.min.js","ext": "./js/贝乐虎.js","style": {"type": "rect","ratio": 1.597}},
{"key": "幸福｜拾光","name": "幸福｜拾光","type": 3,"api": "csp_HBPQ","ext": {"请求头": "User-Agent$MOBILE_UA","编码": "UTF-8","分类": "电影$chfilm#电视剧$chtvs#综艺$chvariety#动漫$chcg#","分类url": "https://www.cgong.com/{cateId}/{class}_{area}_{year}_gold_{catePg}.html","简介": "喜欢热闹还是喜欢安静"}},
{"key": "急救教学","name": "急救｜教学","type": 3,"api": "csp_FirstAid","searchable": 0,"quickSearch": 0,"changeable": 0,"style": {
"type": "rect","ratio": 3.8},"gridview": "0-0-4.1"},
{"key": "家庭养生","name": "家庭｜养生","type": 3,"api": "csp_HBPQ","ext": "./json/YST.json","style": {"type": "rect","ratio": 1.597}},
{"key": "本地","name": "本地｜视频","type": 3,"api": "csp_LocalFile"}],
"parses": [
{"name": "虾米哩","type": 0,"url": "https://jx.xmflv.com/?url=","ext": {"header": {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name": "8090","url": "https://www.8090g.cn/jiexi/?url=","type": 0,"ext": {"flag": ["qiyi","imgo","爱奇艺","奇艺","qq","qq 预告及花絮","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","mgtv","芒果","sohu","xigua","fun","风行"]},"header": {"User-Agent": "Mozilla/5.0"}},
{"name": "剖云","type": 0,"url": "https://www.pouyun.com/?url="},
{"name": "全能","type": 0,"url": "https://jx.xmflv.com/?url=","ext": {"flag": ["bilibili1","qiyi","imgo","爱奇艺","奇艺","qq","qq 预告及花絮","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","mgtv","芒果","sohu","xigua","fun","风行"],"header": {"User-Agent": "okhttp/4.1.0"}}},
{"name": "虾米","type": 0,"url": "https://jx.xmflv.com/?url=","ext": {
"header": {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name": "虾米2","url": "https://jx.xmflv.cc/?url=","type": 0,"ext": {"flag": ["qiyi","imgo","爱奇艺","奇艺","qq","qq 预告及花絮","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","mgtv","芒果","JL4K","sohu","xigua","fun","风行"]},"header": {"User-Agent": "Mozilla/5.0"}},
{"name": "淘片","type": 0,"url": "https://jx.yparse.com/index.php?url=","ext": {
"header": {"user-agent": "Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
}}},
{"name": "冰豆","type": 0,"url": "https://bd.jx.cn/?url=","ext": {
"header": {"user-agent": "Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name": "盘古","type": 0,"url": "https://www.playm3u8.cn/jiexi.php?url=","ext": {
"header": {"user-agent": "Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}}
],
"rules": [
{"name": "农民","hosts": ["toutiaovod.com"],"regex": ["video/tos/cn"]},
{"name": "火山","hosts": ["huoshan.com"],"regex": ["item_id="]},
{"name": "抖音","hosts": ["douyin.com"],"regex": ["is_play_url="]},
{"name": "饭团点击","hosts": ["dadagui","freeok","dadagui"],"script": ["document.querySelector(\"#playleft iframe\").contentWindow.document.querySelector(\"#start\").click();"]},
{"name": "毛驴点击","hosts": [
"www.maolvys.com"],"script": ["document.getElementsByClassName('swal-button swal-button--confirm')[0].click()"]},
{"name": "ofiii","hosts": ["www.ofiii.com"],"script": ["const play=document.getElementsByClassName('play_icon')[0],event=new MouseEvent('click',{bubbles:!0,cancelable:!0,view:window,screenX:100,screenY:100,clientX:50,clientY:50,button:0,shiftKey:!1,ctrlKey:!1,altKey:!1,metaKey:!1,modifierState:0});play.dispatchEvent(event);"]
}],
"doh": [{"name": "AliDNS","url": "https://dns.alidns.com/dns-query","ips": ["223.5.5.5","223.6.6.6"]},
 {"name": "114DNS","url": "https://dns.alidns.com/dns-query","ips": ["114.114.114.114","114.114.115.115"]}],
"hosts": [
"cache.ott.*.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com",
"cache.ott.ystenlive.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com",
"cache.ott.bestlive.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com",
"cache.ott.wasulive.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com",
"cache.ott.fifalive.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com",
"cache.ott.hnbblive.itv.cmvideo.cn=base-v4-free-mghy.e.cdn.chinamobile.com"],
"flags": [
"youku","优酷","优 酷","优酷视频","qq","腾讯",
"腾 讯","腾讯视频","iqiyi","qiyi","奇艺","爱奇艺","爱 奇 艺","m1905","xigua","letv","leshi","乐视","乐 视","sohu","搜狐","搜 狐","搜狐视频","tudou","pptv","mgtv","芒果","imgo","芒果TV","芒 果 T V","bilibili","哔 哩","哔 哩 哔 哩"],
"ijk": [
{"group": "软解码","options": [
{"category": 4,"name": "opensles","value": "0"},
{"category": 4,"name": "overlay-format","value": "842225234"},
{"category": 4,"name": "framedrop","value": "1"},
{"category": 4,"name": "soundtouch","value": "1"},
{"category": 4,"name": "start-on-prepared","value": "1"},
{"category": 1,"name": "http-detect-range-support","value": "0"},
{"category": 1,"name": "fflags","value": "fastseek"},
{"category": 2,"name": "skip_loop_filter","value": "48"},
{"category": 4,"name": "reconnect","value": "1"},
{"category": 4,"name": "enable-accurate-seek","value": "0"},
{"category": 4,"name": "mediacodec","value": "0"},
{"category": 4,"name": "mediacodec-auto-rotate","value": "0"},
{"category": 4,"name": "mediacodec-handle-resolution-change","value": "0"},
{"category": 4,"name": "mediacodec-hevc","value": "0"},
{"category": 1,"name": "dns_cache_timeout","value": "600000000"}]},
{"group": "硬解码","options": [
{"category": 4,"name": "opensles","value": "0"},
{"category": 4,"name": "overlay-format","value": "842225234"},
{"category": 4,"name": "framedrop","value": "1"},
{"category": 4,"name": "soundtouch","value": "1"},
{"category": 4,"name": "start-on-prepared","value": "1"},
{"category": 1,"name": "http-detect-range-support","value": "0"},
{"category": 1,"name": "fflags","value": "fastseek"},
{"category": 2,"name": "skip_loop_filter","value": "48"},
{"category": 4,"name": "reconnect","value": "1"},
{"category": 4,"name": "enable-accurate-seek","value": "0"},
{"category": 4,"name": "mediacodec","value": "1"},
{"category": 4,"name": "mediacodec-auto-rotate","value": "1"},
{"category": 4,"name": "mediacodec-handle-resolution-change","value": "1"},
{"category": 4,"name": "mediacodec-hevc","value": "1"},
{"category": 1,"name": "dns_cache_timeout","value": "600000000"}]}],
"ads": ["static-mozai.4gtv.tv"]}